name: Barkeep CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Check Coding Standards
      run: |
        pylint main.py
        pylint src
        pylint tests

    - name: Check types
      run: mypy .

    - name: Check formatting
      run: black . --check --verbose
